name: walkthrough1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: 5.3.1       # compatible with Dart <3
  http: ^0.13.6             # last version before Dart 3 requirement
  flutter_map: ^2.2.0       # compatible with Flutter 2.x
  latlong2: ^0.8.1          # works with Dart 2.x
  timeline_tile: ^1.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
